Game:
  port: 8082
  MapPaths:
    - Map: { name: Map1, path: ''}
    - Map: { name: Map2, path: ''}
  Weapons:
    - Weapon: { name: IDF, bulletdamage: 10, firerate: 20, reloadafter: 50 }
    - Weapon: { name: P90, bulletdamage: 10, firerate: 10, reloadafter: 30 }
    - Weapon: { name: Scout, bulletdamage: 10, firerate: 1, reloadafter: 20 }
    - Weapon: { name: Grenade, waittime: 10 }
    - Weapon: { name: Bombardeo aereo, waittime: 60 }
  Enemies:
    - Enemy: { name: Infectado, speed: 10 }
    - Enemy: { name: Jumper, speed: 10 }
    - Enemy: { name: Witch, speed: 10 }
    - Enemy: { name: Spear, speed: 10 }
    - Enemy: { name: Venom, speed: 10 }
  Soldiers:
    - Soldier: { 
      gun: IDF, 
      grenades: true, 
      bombardeo: false, 
      walk sprites: 7,
      run sprites: 8,
      idle sprites: 7,
      hurt sprites: 3,
      recharge sprites: 13,
      shot1 sprites: 4,
      shot2 sprites: 4,
      grenade sprites: 9,
      dead sprites: 4,
      attack sprites: 3
      }
    - Soldier: { 
      gun: P90, 
      grenades: true, 
      bombardeo: true, 
      walk sprites: 8,
      run sprites: 8,
      idle sprites: 9,
      hurt sprites: 3,
      recharge sprites: 7,
      shot1 sprites: 4,
      shot2 sprites: 4,
      grenade sprites: 16,
      dead sprites: 4,
      attack sprites: 4
      }
    - Soldier: { 
      gun: Scout, 
      grenades: true, 
      bombardeo: false, 
      walk sprites: 8,
      run sprites: 6,
      idle sprites: 7,
      hurt sprites: 4,
      recharge sprites: 8,
      shot1 sprites: 4,
      shot2 sprites: 4,
      grenade sprites: 8,
      dead sprites: 5,
      attack sprites: 5,
      smoke sprites: 22
      }
