SERVER_PORT: 9091
HP_BAR_LENGTH: 50
HP_BAR_HEIGHT: 3
Y_OFFSET: 505
GAME_FRAME_RATE: 30
MIN_MAX_VOLUME: 128
GAME_VOLUME: 10
RESOLUTION_X: 1920
LAG_CONSTANT: 4000
MIXER_CHANNELS: 4
GAME_TICK_RATE: 10
ZOMBIE_CREATION_TIME_MIN: 10000
ZOMBIE_CREATION_TIME_MAX: 15000
SCORE_TO_WIN: 10
MAX_ZOMBIES: 4
MAX_PLAYERS: 1
DEFAULT_MODE: 1
MUSIC: 0
WAIT_TIME_START_GAME: 10000
CTA_NUMBER_OF_ZOMBIES: 25
RESPAWN_TIME: 100
BULLET_SPEED: 95
BULLET_HITBOX: 10
BULLET_SHOT_OFFSET: 0
ARMA1_DAMAGE: 20
ARMA1_BULLET_COUNT: 20
ARMA1_MAGAZINE: 50
ARMA1_RELOAD_DELAY: 40
ARMA1_SHOOT_DELAY: 20
ARMA1_GRENADE_DELAY: 200
ARMA2_DAMAGE: 6
ARMA2_BULLET_COUNT: 10
ARMA2_MAGAZINE: 30
ARMA2_RELOAD_DELAY: 10
ARMA2_SHOOT_DELAY: 20
ARMA2_GRENADE_DELAY: 500
ARMA3_DAMAGE: 150
ARMA3_BULLET_COUNT: 1
ARMA3_MAGAZINE: 10
ARMA3_RELOAD_DELAY: 20
ARMA3_SHOOT_DELAY: 10
ARMA3_GRENADE_DELAY: 200
GRANADA_DAMAGE: 95
AIR_STRIKE_DAMAGE: 45
SMOKE_DAMAGE: 0
GRANADA_DELAY_12: 10
GRANADA_DELAY_23: 0
GRANADA_DELAY_3: 5
GRANADA_SIZE: 128
GRANADA_FUERZA: 30
BOMBARDER_SPACE_IN_BETWEEN: 250
DEFAULT_MAX_X: 3000
DEFAULT_MAX_Y: 145
EVENTS_PER_LOOP: 20
SPAWNER_SAFE_AREA_X: 300
CODE_NULL: 0
CODE_VENOM_PROJECTILE: 3
CODE_WITCH_SPAWN: 4
PLAYER_RECT_WIDTH: 20
PLAYER_RECT_HEIGHT: 70
PLAYER_SPEED: 10
PLAYER_HP: 500
PLAYER_HP_AFTER_REVIVE: 100
ZOMBIE_RECT_WIDTH: 96
ZOMBIE_RECT_HEIGHT: 96
SPEAR_RECT_WIDTH: 128
SPEAR_RECT_HEIGHT: 128
VENOM_RECT_WIDTH: 128
VENOM_RECT_HEIGHT: 128
ZOMBIE_HP: 100
ZOMBIE_SEEKING_DISTANCE: 400
ZOMBIE_DAMAGE: 0
ZOMBIE_SPEED: 4
ZOMBIE_TIMER: 15
ZOMBIE_IMPAIRED_TIME: 50
SPEAR_DAMAGE: 0
SPEAR_HP: 150
SPEAR_SPEED: 5
SPEAR_SEEKING_DISTANCE: 2000
VENOM_SEEKING_DISTANCE: 2000
VENOM_HP: 50
VENOM_SPEED: 2
VENOM_PROJECTILE_COOLDOWN: 20
VENOM_PROJECTILE_DAMAGE: 30
VENOM_PROJECTILE_SPEED: 20
VENOM_PROJECTILE_SIZE: 20
VENOM_DAMAGE: 0
WITCH_SEEKING_DISTANCE: 800
WITCH_HP: 255
WITCH_SCREAM_CHANCE: 50
WITCH_SPAWN_CHANCE: 50
JUMPER_SEEKING_DISTANCE: 500
JUMPER_DAMAGE: 0
JUMPER_HP: 50
JUMPER_SPEED: 20
JUMPER_COOLDOWN: 40