#renderer
HP_BAR_LENGTH: 50
HP_BAR_HEIGHT: 3
Y_OFFSET: 505
GAME_FRAME_RATE: 30
MIN_MAX_VOLUME: 128
GAME_VOLUME: 10
RESOLUTION_X: 1920

#game.h
GAME_TICK_RATE: 5
ZOMBIE_CREATION_TIME_MIN: 10000
ZOMBIE_CREATION_TIME_MAX: 15000
SCORE_TO_WIN: 10
MAX_ZOMBIES: 4
MAX_PLAYERS: 1
WAIT_TIME_START_GAME: 10000

#playerstate.h
RESPAWN_TIME: 100

#armas
ARMA1_DAMAGE: 5
ARMA1_BULLET_COUNT: 20
ARMA1_MAGAZINE: 50
ARMA1_RELOAD_DELAY: 40
ARMA1_SHOOT_DELAY: 20
ARMA1_GRENADE_DELAY: 10

ARMA2_DAMAGE: 6
ARMA2_BULLET_COUNT: 10
ARMA2_MAGAZINE: 30
ARMA2_RELOAD_DELAY: 10
ARMA2_SHOOT_DELAY: 20
ARMA2_GRENADE_DELAY: 3000

ARMA3_DAMAGE: 150
ARMA3_BULLET_COUNT: 1
ARMA3_MAGAZINE: 10
ARMA3_RELOAD_DELAY: 20
ARMA3_SHOOT_DELAY: 10
ARMA3_GRENADE_DELAY: 1000

#granadas

GRANADA_DAMAGE: 95
GRANADA_DELAY_12: 10 #tiempo en explotar
GRANADA_DELAY_23: 0  #tiempo en aparecer: humo
GRANADA_DELAY_3: 15  #tiempo en desaparecer el humo
GRANADA_SIZE: 128
GRANADA_FUERZA: 30   #distancia por tick de tecla apretada


# common
DEFAULT_MAX_X: 3000
DEFAULT_MAX_Y: 145
EVENTS_PER_LOOP: 20

#zombie calculate_next_movement code
CODE_NULL: 0
CODE_VENOM_PROJECTILE: 3
CODE_WITCH_SPAWN: 4

# Player
PLAYER_RECT_WIDTH: 20
PLAYER_RECT_HEIGHT: 20
PLAYER_SPEED: 20
PLAYER_HP: 100

# Zombie
ZOMBIE_RECT_WIDTH: 20
ZOMBIE_RECT_HEIGHT: 20
ZOMBIE_HP: 100
ZOMBIE_SEEKING_DISTANCE: 400
ZOMBIE_DAMAGE: 5
ZOMBIE_SPEED: 8
ZOMBIE_TIMER: 15

# Spear
SPEAR_RECT_WIDTH: 100
SPEAR_DAMAGE: 7
SPEAR_HP: 150
SPEAR_SPEED: 10
SPEAR_SEEKING_DISTANCE: 2000

# Venom
VENOM_RECT_WIDTH: 96
VENOM_SEEKING_DISTANCE: 2000
VENOM_HP: 50
VENOM_SPEED: 4
VENOM_PROJECTILE_COOLDOWN: 20
VENOM_PROJECTILE_DAMAGE: 50
VENOM_PROJECTILE_SPEED: 40
VENOM_PROJECTILE_SIZE: 20
VENOM_DAMAGE: 3

#Witch
WITCH_SEEKING_DISTANCE: 800
WITCH_HP: 255

#Jumper
JUMPER_SEEKING_DISTANCE: 500
JUMPER_DAMAGE: 45
JUMPER_HP: 50
JUMPER_SPEED: 20
JUMPER_COOLDOWN: 20
