Game:
  port: 8082
  default_max_x: 1920
  default_max_y: 145
  events_per_loop: 20
  Gameloop: 
    game_tick_rate: 5
    zombie_creation_time_min: 10000
    zombie_creation_time_max: 15000
    score_to_win: 10
    max_zombies: 4
    max_players: 1
    wait_time_start_game: 10000
  Playerstate: 
    hp: 100
    width: 20
    height: 20
    respawn_time: 100
    speed: 20
    gun_magazine_size: 10
  MapPaths:
    - Map: { name: Map1, path: ''}
    - Map: { name: Map2, path: ''}
  Weapons:
    - IDF: { 
        damage: 5,
        bulletcount: 20,
        magazine: 50,
        shootdelay: 20,
        reloaddelay: 50,
        grenadedelay: 10,
        grenadetype: 1,
        grenadepower: 30
      }
    - P90: { 
        damage: 6,
        bulletcount: 10,
        magazine: 30,
        shootdelay: 20,
        reloaddelay: 30,
        grenadedelay: 3000,
        grenadetype: 2,
        grenadepower: 30
      }
    - Scout: { 
        damage: 150,
        bulletcount: 1,
        magazine: 10, 
        shootdelay: 10,
        reloaddelay: 20,
        grenadedelay: 1000,
        grenadetype: 3,
        grenadepower: 30 
      }
    - Grenade: { 
        exploding_delay: 10,
        smoke_appearance_delay: 0,
        smoke_disappearance_delay: 15,
        size: 128,
        fuerza: 30
      }
    - Bombardeo aereo: {
        waittime: 60 
      }
  Enemies:
    - Zombie: { 
        speed: 4,
        rect_width: 20,
        rect_height: 20,
        seeking_distance: 400,
        damage: 5,
        hp: 100,
        cooldown: 0,
        timer: 15
      }
    - Jumper: { 
        speed: 10,
        rect_width: 20,
        rect_height: 20,
        seeking_distance: 300,
        damage: 45,
        hp: 50,
        cooldown: 20,
        timer: 15
      }
    - Witch: {
        speed: 0,
        rect_width: 20,
        rect_height: 20,
        seeking_distance: 800,
        damage: 0,
        hp: 255,
        cooldown: 0,
        timer: 15
      }
    - Spear: { 
        speed: 3,
        rect_width: 100,
        rect_height: 20,
        seeking_distance: 0,
        damage: 0,
        hp: 150,
        cooldown: 0,
        timer: 15
      }
    - Venom: {  
        speed: 2,
        rect_width: 96,
        rect_height: 20,
        seeking_distance: 1000,
        damage: 3,
        hp: 50,
        cooldown: 0,
        timer: 15,
        projectile_cooldown: 20,
        projectile_damage: 50,
        projectile_speed: 10
      }
  Soldiers:
    - Soldier: { 
      grenades: 1, 
      bombardeo: 0, 
      walk frames: 7,
      run frames: 8,
      idle frames: 7,
      hurt frames: 3,
      recharge frames: 13,
      shot1 frames: 4,
      shot2 frames: 4,
      grenade frames: 9,
      dead frames: 4,
      attack frames: 3
      }
    - Soldier: { 
      grenades: 1, 
      bombardeo: 1, 
      walk frames: 8,
      run frames: 8,
      idle frames: 9,
      hurt frames: 3,
      recharge frames: 7,
      shot1 frames: 4,
      shot2 frames: 4,
      grenade frames: 16,
      dead frames: 4,
      attack frames: 4
      }
    - Soldier: { 
      grenades: 1, 
      bombardeo: 0, 
      walk frames: 8,
      run frames: 6,
      idle frames: 7,
      hurt frames: 4,
      recharge frames: 8,
      shot1 frames: 4,
      shot2 frames: 4,
      grenade frames: 8,
      dead frames: 5,
      attack frames: 5,
      smoke frames: 22
      }
  Math: {
    codenull: 0,
    code venom projectile: 3,
    code witch spawn: 4
  }