SERVER_PORT: 9091

#renderer
HP_BAR_LENGTH: 50
HP_BAR_HEIGHT: 3
Y_OFFSET: 505
GAME_FRAME_RATE: 30
MIN_MAX_VOLUME: 128 #NO CAMBIAR
GAME_VOLUME: 10
RESOLUTION_X: 1920
LAG_CONSTANT: 4000 #SE PUEDE SUBIR SI EL TICK RATE ES ALTO
MIXER_CHANNELS: 4

#game.h
GAME_TICK_RATE: 10 #SI SE DUPLICA, BAJAR A LA MITAD TODOS LOS DAÑOS Y VELOCIDADES DE ZOMBIES PARA MANTENER VELOCIDAD/DAÑO REAL
ZOMBIE_CREATION_TIME_MIN: 10000
ZOMBIE_CREATION_TIME_MAX: 15000
SCORE_TO_WIN: 10
MAX_ZOMBIES: 4
MAX_PLAYERS: 1
DEFAULT_MODE: 1
MUSIC: 0
WAIT_TIME_START_GAME: 10000
CTA_NUMBER_OF_ZOMBIES: 25

#playerstate.h
RESPAWN_TIME: 100

#armas
BULLET_SPEED: 95
BULLET_HITBOX: 10
BULLET_SHOT_OFFSET: 0 #DE DONDE SALE LA BALA RESPECTO AL JUGADOR, CON 0 ESTA BIEN, PERO SE PUEDE CAMBIAR
#PARECE NO HACER NADA, LA BALA SALE DE LOS OJOS DEL PLAYER SIEMPRE

ARMA1_DAMAGE: 20
ARMA1_BULLET_COUNT: 20
ARMA1_MAGAZINE: 50
ARMA1_RELOAD_DELAY: 40
ARMA1_SHOOT_DELAY: 20
ARMA1_GRENADE_DELAY: 200 #HE

ARMA2_DAMAGE: 6
ARMA2_BULLET_COUNT: 10
ARMA2_MAGAZINE: 30
ARMA2_RELOAD_DELAY: 10
ARMA2_SHOOT_DELAY: 20
ARMA2_GRENADE_DELAY: 500 #BOMBARDER

ARMA3_DAMAGE: 150
ARMA3_BULLET_COUNT: 1
ARMA3_MAGAZINE: 10
ARMA3_RELOAD_DELAY: 20
ARMA3_SHOOT_DELAY: 10
ARMA3_GRENADE_DELAY: 200 #SMOKE

#granadas
GRANADA_DAMAGE: 95
AIR_STRIKE_DAMAGE: 45
SMOKE_DAMAGE: 0

GRANADA_DELAY_12: 10 #tiempo en explotar
GRANADA_DELAY_23: 0  #tiempo en aparecer: humo
GRANADA_DELAY_3: 5  #tiempo en desaparecer el humo
GRANADA_SIZE: 128
GRANADA_FUERZA: 30   #distancia por tick de tecla apretada
BOMBARDER_SPACE_IN_BETWEEN: 250 #distancia entre bombas del bombardero

# common
DEFAULT_MAX_X: 3000
DEFAULT_MAX_Y: 145
EVENTS_PER_LOOP: 20

#zombie spawn
SPAWNER_SAFE_AREA_X: 300

#zombie calculate_next_movement code
CODE_NULL: 0
CODE_VENOM_PROJECTILE: 3
CODE_WITCH_SPAWN: 4

# Player
PLAYER_RECT_WIDTH: 20 #si pongo estos en 128 es muy mentira la hitbox
PLAYER_RECT_HEIGHT: 70
PLAYER_SPEED: 10
PLAYER_HP: 100
PLAYER_HP_AFTER_REVIVE: 100

#Zombie hitboxes
ZOMBIE_RECT_WIDTH: 96 #todos los zombies de 96px son common, jumper, witch
ZOMBIE_RECT_HEIGHT: 96

SPEAR_RECT_WIDTH: 128
SPEAR_RECT_HEIGHT: 128

VENOM_RECT_WIDTH: 128
VENOM_RECT_HEIGHT: 128


# Zombie
ZOMBIE_HP: 100
ZOMBIE_SEEKING_DISTANCE: 400
ZOMBIE_DAMAGE: 2
ZOMBIE_SPEED: 4
ZOMBIE_TIMER: 15
ZOMBIE_IMPAIRED_TIME: 50

# Spear
SPEAR_DAMAGE: 4
SPEAR_HP: 150
SPEAR_SPEED: 5
SPEAR_SEEKING_DISTANCE: 2000

# Venom
VENOM_SEEKING_DISTANCE: 2000
VENOM_HP: 50
VENOM_SPEED: 2
VENOM_PROJECTILE_COOLDOWN: 20
VENOM_PROJECTILE_DAMAGE: 30
VENOM_PROJECTILE_SPEED: 20
VENOM_PROJECTILE_SIZE: 30
VENOM_DAMAGE: 2

#Witch
WITCH_SEEKING_DISTANCE: 800
WITCH_HP: 255
WITCH_SCREAM_CHANCE: 50
WITCH_SPAWN_CHANCE: 50

#Jumper
JUMPER_SEEKING_DISTANCE: 500
JUMPER_DAMAGE: 20
JUMPER_HP: 50
JUMPER_SPEED: 20
JUMPER_COOLDOWN: 40
